💡 refactor & 🟢 feat : post CRUD
mobi-MIMIZ/PostMobism pull request #46
Opened 2024-02-17 09:26 UTC by 55555-Jyeon

## 개요

16일 리팩터링된 코드에 맞춰 기능 구현 다시 진행했습니다.
readme.md 내용 추가했습니다. (ETA + 시연 영상)

대부분 구현 완료되었으나 자잘한 issue가 존재합니다. 

## PR 유형

어떤 변경 사항이 있나요?

-   [x] 🟢 feat : 새로운 기능 추가
-   [ ] 🔴 Remove : 파일이나 폴더를 삭제하는 작업만 수행한 경우
-   [ ] 🔥 HOTFIX : 급하게 치명적인 버그를 고쳐야하는 경우
-   [ ] 🐞 fix : 버그수정
-   [x] 🎁 style : CSS 등 사용자 UI 디자인 변경
-   [ ] 💬 Comment : 필요한 주석 추가 및 변경
-   [x] 💡 refactor : 기능, 코드 개선
-   [ ] 🔖 Rename : 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
-   [x] 📂 docs : 문서 수정

## PR Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

-   [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
-   [x] 직접 만든 함수가 있다면 이에 대한 설명을 추가했습니다. (ex. JS DOCS)
-   [x] 변경 사항에 대한 테스트를 했습니다. (버그 수정/기능에 대한 테스트)

## PR details

[ postRead ]

페이지네이션 기능 구현을 위해 목데이터를 불러오던 부분을 실제 백엔드 데이터로 변경했습니다.

https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/8772f327-3d17-42c6-8f08-4f75e18f733e

<img width="1829"  src="https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/142ad948-6c51-4f3c-8d82-e3ea34df1240">

[ postCreate ]  

이미지 추가하는 기능은 있었으나 detail-post-modal에 업로드한 이미지를 보여주는 부분이 누락되어 있었습니다.
디자인 및 기능 추가해 업로드한 이미지를 볼 수 있도록 변경했습니다.

https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/a19ab55f-4faa-47be-91e6-244821c49631

<br />

[ postDelete ] 

api가 정리된 notion의 example을 위주로 참고하느라 잘못된 경로로 데이터를 전달하고 있어 404 에러가 뜨는 이슈가 있었습니다.
update도 delete도 같은 문제가 있었고 이 부분 때문에 적지 않은 시간이 소요됐습니다.

현재는 게시글이 잘 지워지고 있습니다.
게시글 삭제 후 detail-post-modal이 닫히도록 관련 상태를 전역으로 관리하는 것을 추가해야 합니다.

https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/7cfa92ab-0543-4ccd-81de-e712244239e8

<br />

[ postUpdate ] 

게시글 수정하는 디자인이 없어 디자인부터 만들었습니다.
post 수정 후 detail-post-modal이 닫히는 것이 나을지 수정된 부분을 확인할 수 있게 닫지 않는 것이 나을지 얘기해보고 싶습니다 :)

https://github.com/mobi-MIMIZ/PostMobism/assets/134191817/be54ef16-3b67-4fa2-825b-184bfc362261

<br />

2024-02-18 16:39 UTC, kiminn commented on src/features/post/post.api.ts
> +    })
이렇게하면 타입추론이  마우스 올려봤을 때 잘 안되는 거로 알고 있습니다!

typescript의 장점을 활용하기 위해 이렇게 바꾸는 건 어떨까요?
```tsx
  async postPost({ title, content }: { title: string; content: string }) {
    const postData = { title, content }
    const res = await axiosInstance.post(POST_PATH, postData, {
      //auth:true.. (dataUser:null => console창 문제)
      params: { auth: "true" },
    })
    return res.data
  },
```

2024-02-18 16:40 UTC, kiminn commented on src/features/post/post.api.ts
> +      data: req,
여기 이런식으로요 좋네용!

2024-02-18 16:42 UTC, kiminn commented on src/features/post/post.slice.ts
> +export const postPost = createAsyncThunk<Post, { formData: FormData }>("post/postPost", async ({ formData }) => {
여기도 변경하면 좋을 거 같습니다!

2024-02-18 16:45 UTC, kiminn commented on src/pages/main/components/post-detail-modal/post-detail-modal.tsx
> +  }
```tsx
const handleScroll = () => {
    const { scrollHeight, scrollTop, clientHeight } = document.documentElement;
    const isScrolledToBottom = scrollTop + clientHeight >= scrollHeight;
    if (isScrolledToBottom) {
        setPage(prevPage => prevPage + 1);
    }
}
```
이런식으로 로직을 줄일 수도 있을 거 같아요!

2024-02-18 16:47 UTC, kiminn requested changes
고생하셨습니다

UPDATE 와 DELETE하는 과정에서 썬더로 계속 데이터 찍어보는데 에러나고ㅠ
쉽지 않았던 거 같은데 잘 마무리가 되어서 다행이에요 👍

2024-02-18 16:49 UTC, kiminn approved these changes

2024-02-18 19:52 UTC, 55555-Jyeon commented on src/features/post/post.api.ts
> +    })
엇, 그 부분은 Kimi 님과 Peanut 님이 첫 번째 리팩터링 시간 갖은 뒤 PR 올려주셨던 내용에서 가져온 건데... 😮

다른 post api는 위와 같은 형태로 작성되어 있습니다,  안 그래도 postPost 부분만 formData로 되어 있어서 이상하게 생각했는데
변경할게요.

2024-02-18 20:03 UTC, 55555-Jyeon commented on src/features/post/post.api.ts
> +      data: req,
아, 위 부분은 다른 api 주소와 통일성 주기 위해 변경해서 commit 할 예정이었습니다!
처음에 example만 참고하다가 잘못된 주소로 요청을 하고 있던 곳이 있었습니다. (아마 update랑 delete..?)
그래서 주소를 url과 똑같이 전달해서 테스트하기 위해 위와 같이 문자열로 표현 후 정상적으로 요청이 되면 변경할 예정이던 부분이에요.

위 방식은 +를 사용한 문자열 연결 방식으로 URL을 문자열로 직접 조합해 사용하는 겁니다.
문자열 연결 방식을 사용할 경우 가독성이 떨어질 수 있고, 코드가 길어질수록 실수가 발생하기 쉬울 수 있다는 단점이 있습니다. 
게다가 파라미터를 명시적으로 표현하지 않기 때문에 어떤 파라미터가 전달되는지 알기 어렵습니다.

저희가 주로 사용하던 방식은 파라미터 객체를 사용하는 거였습니다.
이 방식은 URL과 파라미터를 분리하여 코드를 작성하기 때문에 URL은 더 간결하게 표현되며, 파라미터는 객체로 명시적으로 표현됩니다. 이렇게 하면 가독성이 향상되며, 파라미터를 쉽게 추가하거나 수정할 수 있습니다. 
또한, Axios는 내부적으로 URL을 올바르게 인코딩하므로 특수 문자 등을 처리하는 데 도움이 된다고 합니다.

두 방식 모두 선호도에 따라 선택할 수 있지만 보통은 파라미터 객체 사용 방식이 코드의 가독성과 유지보수 측면에서 더 좋기 때문에 이 방법으로 통일할 예정이었습니다!

2024-02-18 20:05 UTC, 55555-Jyeon commented on src/pages/main/components/post-detail-modal/post-detail-modal.tsx
> +  }
위 코드는 comment의 무한 스크롤과 관련 있는 부분이라 아마 Kimi 님 PR과 합칠 때 변경될 부분이지 않을까 싶습니다

2024-02-18 20:11 UTC, 55555-Jyeon commented on src/features/post/post.slice.ts
> +export const postPost = createAsyncThunk<Post, { formData: FormData }>("post/postPost", async ({ formData }) => {
일괄 변경 후 추가 commit 했습니다!

2024-02-18 20:13 UTC, 55555-Jyeon commented
> 고생하셨습니다
> 
> UPDATE 와 DELETE하는 과정에서 썬더로 계속 데이터 찍어보는데 에러나고ㅠ 쉽지 않았던 거 같은데 잘 마무리가 되어서 다행이에요 👍

드디어 끝이 났네요 👍🏻

자잘하게 리팩터링해야 되는 항목들 정리해서 git issue에 정리해두었는데 이 부분은 추후 배포할 때 라이브 쉐어로 같이 진행하는게 빠르겠죠..?
더 이상 추가 시간을 할애하기엔 부담이 될 것 같아서 고민입니다.

2024-02-18 20:14 UTC, merged

2024-02-19 09:39 UTC, kiminn commented on src/features/post/post.api.ts
> +    })
엇 저도 변경한 건 없어서 아마 그때 저렇게 올라가 있었을거예요!
넵!! 그냥 formData로하면 타입추론이 잘 되지 않는 거 처럼 보여서요

2024-02-19 09:40 UTC, kiminn commented on src/pages/main/components/post-detail-modal/post-detail-modal.tsx
> +  }
ㅋㅋㅋ아 변경된 거만 보고 말씀드렸네요 맞아요 로직 변경했습니다!

2024-02-19 09:44 UTC, kiminn commented on src/features/post/post.api.ts
> +      data: req,
변경해서 커밋한 내용 확인해보겠습니다!
내용 설명 감사합니당 👍